
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import UserProvider from "@/context/userProvider";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "TaskToDo",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer/>
            <NavBar/>
            {children}
            
      </body>
    </html>
  );
}
